optimizer:
  type: AdamW
  kwargs:
    lr: 1e-5
    weight_decay: 0.05

scheduler:
  type: CosLR
  kwargs:
    epochs: 300
    initial_epochs: 10

dataset:
  train:
    _base_: ReConV2/cfgs/dataset_configs/ModelNet40.yaml
    others:
      subset: train
  val:
    _base_: ReConV2/cfgs/dataset_configs/ModelNet40.yaml
    others:
      subset: test
  test:
    _base_: ReConV2/cfgs/dataset_configs/ModelNet40.yaml
    others:
      subset: test
      
model:
  NAME: PointTransformer
  embed_dim: 384
  depth: 12
  drop_path_rate: 0.2
  cls_dim: 40
  num_heads: 6
  group_size: 32
  num_group: 512
  with_color: False
  large_embedding: False
  img_queries: 13
  text_queries: 3
  decoder_depth: 4

npoints: 8192
total_bs: 32
step_per_update: 1
max_epoch: 300
grad_norm_clip: 10
