optimizer:
  type: AdamW
  kwargs:
    lr: 1e-5
    weight_decay: 0.05

scheduler:
  type: CosLR
  kwargs:
    epochs: 300
    initial_epochs: 10

dataset:
  train:
    _base_: cfgs/dataset_configs/ModelNet40.yaml
    others:
      subset: 'train'
  val:
    _base_: cfgs/dataset_configs/ModelNet40.yaml
    others:
      subset: 'test'
  test:
    _base_: cfgs/dataset_configs/ModelNet40.yaml
    others:
      subset: 'test'
      
model:
  NAME: PointTransformer
  embed_dim: 768
  depth: 12
  drop_path_rate: 0.2
  num_heads: 12
  group_size: 32
  num_group: 512
  with_color: False
  large_embedding: False
  img_queries: 13
  text_queries: 3
  decoder_depth: 4
  pos_threshold: 0.7
  neg_threshold: 0.3
  num_features: 128

npoints: 8192
total_bs: 8
step_per_update: 1
max_epoch: 300
grad_norm_clip: 10
num_workers: 2
